### ISSUE TITLE
SDK does not recognize contract with block comment

### ISSUE THREAD

**Issue by Kevin-Chen0** [fetchai/ledger-api-py#75]
I have tried to create a contract with block comments in it: `/* */`.

`contract = Contract(contract_text, owner)`

However, it is giving me the following error:

```WARNING:root:Etch parsing failed, shard masks will be set to wildcard
WARNING:root:No terminal defined for '*' at line 76 col 2

/*
 ^

Expecting: {'FLOAT_TYPE', 'STRING_LITERAL', 'PRE_UNARY', 'NAME', 'NUMBER', 'BASIC_TYPE', 'FIXED_TYPE'}
```

**Comment by douglasb99** [comment]
Two people at fetch have told me only valid comment  in etch is // and therefore further guidance needed  as this issue will also affect js sdk!

**Comment by wkaluza** [comment]
Multiline comments of the form `/* ... */` are valid in Etch.

**Comment by douglasb99** [comment]
Good to know.
